package queryBuilder.Compiler;

public enum Priority {
    QUERY, SELECT, AVG, COUNT, MIN, MAX, JOIN, ON, WHERE, WHEREINQ, WHEREEQQ, WHEREENDSWITH,
    WHERESTARTSWITH, WHERECONTAINS, WHEREBETWEEN, WHEREIN, PARAMETARLIST, ORWHERE, ANDWHERE,
            GROUPBY, HAVING, ORHAVING, ANDHAVING, ORDERBY, ORDERBYDESC

}
