package errorHandler;

public enum ErrorType
{
    NOTAVALIDKEYWORD, NOTAVALIDTYPE, NONAME, NODATA, NOTAVALIDNAME, NOOPERATION, NOTAVALIDOPERATION, NOALLOCATION,
    NOQUERY, NOTAFUNCTION, INVALIDARGUMENTLENGTH, INVALIDARGUMENTTYPE, EMPTYQUERY, UNHANDLED
}
